name: tests

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - main
      - beta
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code-quality:
    name: 📊 Check code quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run containers
        run: docker-compose -f .ci/docker-compose.yml up -d
      - name: Add hosts
        run: |
          sudo echo "127.0.0.1 sonarr readarr radarr lidarr prowlarr deluge jackett" | sudo tee -a /etc/hosts
      - name: sleep 30s for containers to start-up
        run: sleep 30s
        shell: bash
      - name: check ports are mapped
        run: docker ps
      - name: check one of the containers is up
        run: curl http://radarr:7878
      - name: 🧪 Check tests are passing
        run: |
          pip install poetry nox
          nox -s tests
