---

version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/sonarr/config.xml:/config/config.xml:rw
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/radarr/config.xml:/config/config.xml:rw
    ports:
      - 7878:7878
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/readarr/config.xml:/config/config.xml:rw
    ports:
      - 8787:8787
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/lidarr/config.xml:/config/config.xml:rw
    ports:
      - 8686:8686
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/deluge/config:/config:rw
    ports:
      - 8112:8112
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=123
      - TZ=Europe/London
    volumes:
      - ../tests/docker_configs/jackett/config/jackett:/config:rw
    ports:
      - 9117:9117
    restart: unless-stopped
